guardian/commercial-canaries

src/cmp_ccpa.js
Add an additional step to the CCPA canary that checks for the presence of the top-above-nav selector after:
1. The "do not sell" button has been clicked.
2. A page reload
This is currently running under a `commercial_cmp_test` canary in us-west-1. When this is merged this will be removed and replace `commercial_cmp_ccpa` (currently updated via the manual method as described in the README).
We should be able to detect any future problems with ads loading after a user has clicked the "do not sell" in the CCPA banner.
=> Check CCPA ads after page reload

src/cmp_aus.js, src/cmp_ccpa.js, src/cmp_tcfv2.js
Add more comprehensive checks to the canaries. This checks involve:
-  Performing a follow-up checking on an article without deleting cookies (for both CCPA and TCFv2)
- Bringing AUS checks in line with this new CCPA version.
Note this PR doesn't include checking banners are clicked after clicking buttons in the banner.
Attempt to detect more problems that could arise via canary than we were previously.
=> Add more comprehensive checks

src/cmp_ccpa.js, src/cmp_tcfv2.js
Adds the following checks to the canaries:
- On CCPA, check the CMP banner is hidden after pressing "Do not sell my information"
- On TCFv2, check top-above-nav doesn't load before pressing "Yes I'm happy" in banner.
- On TCFv2, check the CMP banner is hidden after pressing "Yes I'm happy"
- On TCFv2, check the CMP isn't loaded after a page reload (without clearing cookies / local storage)
Hopefully we can detect more CMP / ad loading bugs by checking that ads/CMP aren't displayed at certain points.
=> Add checks that CMP/ads are not displayed at certain points

src/cmp_tcfv2.js
For the TCFv2 canary, wait 5 seconds instead of 1 for the iframe to be loaded into the SourcePoint message container. Additionally, move the wait from before we attempt to click the button to before we attempt to select the iframe from the page.
This change was made as the TCFv2 canary deployed in the Canada region was timing out waiting for the consent banner iframe to load onto the page. Hence we increase the timeout to ensure we give it enough time to load on the page.
=> Increase timeout to load TCFv2 consent banner iframe from 1s to 5s

README.md, cdk/lib/__snapshots__/commercial-canaries.test.ts.snap, cdk/lib/commercial-canaries.ts
1. Updates the synthetics runtime version to the latest.
1. We currently use an S3 bucket to store both canary code and logs for each region. The layout of the bucket is a bit confusing, so choose a new layout which makes it clear where the canary code lives and where the logs (artifacts) live.
We're going FROM:
`lambda: canary-cw-syn-canary-{accountId}-{region}`
`logs: canary-cw-syn-canary-{accountId}-{region}/{stage}`
TO:
`lambda: canary-cw-syn-canary-{accountId}-{region}/{stage}`
`logs: canary-cw-syn-results-{accountId}-{region}/{stage}`
Note that the four `canary-cw-syn-results-{accountId}-{region}` buckets already existed and are unused, which is why they have been repurposed for this.
1. Updates the README. This was out of date following the CDK changes.
=> Update synthetics runtime version

src/cmp_ccpa.js
The update to the SP API means the CCPA message is now served from the `sourcepoint.theguardian.com` instead of the old `ccpa-notice.sp-prod.net`. 
This change ensures the ccpa message iframe is still correctly located
=> Update CCPA Iframe URL

cdk/lib/__snapshots__/commercial-canaries.test.ts.snap, cdk/lib/commercial-canaries.ts, src/cmp_aus.js, src/cmp_ccpa.js
Use the try/catch/finally block to ensure that `browser.close()` is called in the Australia and US regions, to bring the lambda functions in line with the the lambda functions in the TCF regions (Ireland and Canada).
This should alleviate our problems with this particular error in the Australia region this morning:
=> Ensure the browser is closed for the AUS/US canaries

README.md, cdk/lib/__snapshots__/commercial-canaries.test.ts.snap, cdk/lib/commercial-canaries.ts, src/cmp_aus.js, src/cmp_ccpa.js, src/cmp_tcfv2.js
The previous commit silenced errors thrown by the run with the `catch` clause. We do not want this catch clause, because when an action fails (e.g. checking for ads), we want the run to fail. We still want the finally clause, since we want the browser to be closed after every run
So that canary runs fail when an error is thrown
=> BUG: Fix catch issue

.github/scripts/create-artifacts.sh, .github/workflows/deploy.yaml, cdk/lib/__snapshots__/commercial-canaries.test.ts.snap, cdk/lib/commercial-canaries.ts, cdk/package.json, cdk/yarn.lock, src/cmp_aus.js, src/cmp_ccpa.js, src/cmp_tcfv2.js, yarn.lock
In the src folder of the repository are three lambda functions, each designed to be run in one or more regions as AWS Synthetics Canaries. When we make a change to one or more of these lambda files, then create a branch and push, we would expect the test canaries in AWS to be updated with our new code. Similarly, when we merge code to main, we would expect our production canaries to be updated. However, there is a problem. When CloudFormation receives instructions to update the canary stack, it will not update the canary if the changeset is empty. The lambda code is stored in a bucket in S3 and referenced in the yaml template. This location in S3 doesn’t change, since we overwrite old versions, so CloudFormation doesn’t detect any changes to the stack and therefore doesn’t run the update. …
=> Trigger CloudFormation to run whenever Lambda code is changed

README.md, src/cmp_aus.js, src/cmp_ccpa.js, src/cmp_tcfv2.js
Co-authored-by @domlander 
A simple PR to add a time to the canary log messages.
OId format: `INFO GUCanaryRun. Message: {message}`
New format: `INFO GUCanaryRun {seconds elapsed}s. Message: {message}`
=> Added a timer to the log messages

cdk/yarn.lock, package.json, yarn.lock
Removed unnecessary dependencies from the `package.json` files and recreated the `yarn.lock` files in the root folder and in the `/cdk` folder.
Our Snyk integration had reported inconsistencies with one of the packages referenced in the yarn lock file. The error message provided suggested that recreating our yarn lock file would fix the issue. However, after deleting and recreating the yarn lock file, the issue persisted.
**Failed run:** https://github.com/guardian/commercial-canaries/runs/7148726570?check_suite_focus=true
**Error:** `Dependency tar-fs@^2.1.1 was not found in yarn.lock. Your package.json and yarn.lock are probably out of sync. Please run "yarn install" and try again.`
I have rerun the Snyk Github Action and it passes on this branch: …
=> Fix issue that causes Snyk Github Action to fail

.github/workflows/deploy.yaml
- Let Riffraff manage the [stack policy](https://riffraff.gutools.co.uk/docs/magenta-lib/types#cloudformation) for all regions except for US
- Adds a comment to explain why we set manageStackPolicy to false in the US in our riffraff template
If we set manageStackPolicy to true in our riffraff template, we get the following error:
`Error validating stack policy: Unknown resource type 'AWS::DocDB::DBCluster'`
This is because Amazon DocumentDB is not supported in the us-east-1 region. You can see the stack policy that Riffraff manages for us [here](https://riffraff.gutools.co.uk/docs/magenta-lib/types#cloudformation). We would prefer to allow Riffraff to manage our stack policy, but this is currently impossible in the us-east-1 region.
=> Add comment to explain why we do not let Riffraff manage stack policy in US

src/cmp_aus.js
This is a test to verify if the CMP isn't persisting the user choice because we reload the page too quickly after clicking 'continue'.
=> Test if adding a timeout helps the CMP work in aus

src/cmp_ccpa.js
Since Wednesday ~14:00 we've had failures in US and Aus. It appears that SP needs more to persist the user's choice and reloading the page too quickly after clicking 'continue' means the choice hasn't been saved. This change introduces a 5 second delay before reloading the page.
A corresponding change has already been made to the aus script.
=> Adding a delay after clicking 'continue'

src/cmp_aus.js, src/cmp_ccpa.js, yarn.lock
Follow on from https://github.com/guardian/commercial-canaries/pull/33 and https://github.com/guardian/commercial-canaries/pull/32 which added a 5 second delay after interacting with the CMP to allow SP to save the change.
> Since Wednesday ~14:00 we've had failures in US and Aus. It appears that SP needs more to persist the user's choice and reloading the page too quickly after clicking 'continue' means the choice hasn't been saved. This change introduces a 5 second delay before reloading the page.
This change moves the delay from the script part of the file to the `interactWithCMP` function itself (where it belongs).
This also reduces the 5 send delay to 1.5s because SP has assured us it doesn't take that long to persist the change.
=> Update to wait behaviour

.github/workflows/deploy.yaml
Riff-Raff offers some protection for stateful resources during a CloudFormation deployment, however there was a bug when this is performed in the us-west-1 region, and we've opted out by setting `manageStackPolicy` to `false`. https://github.com/guardian/riff-raff/pull/874 patches Riff-Raff, removing the need for this workaround. See the Riff-Raff PR for more detail.
- Deploy https://github.com/guardian/riff-raff/pull/874 to Riff-Raff CODE
- Deploy this branch to CODE
- Observe Riff-Raff performing a CloudFormation deployment in the us-west-1 region, without error
More protection from Riff-Raff, and no more [scary messages](https://github.com/guardian/riff-raff/pull/872) in the build log!
=> cd: Remove Riff-Raff configuration workaround

cdk/lib/__snapshots__/commercial-canaries.test.ts.snap, cdk/lib/commercial-canaries.ts
Adds `s3:DeleteObject` to the canary IAM role, this is just a hunch because I can't see any signs of the canary complaining about this, but is certainly a barrier.
It's already set up to delete old results with the `successRetentionPeriod` and `failureRetentionPeriod` attributes.
This should solve the problem of the retention rules not being obeyed, and reports piling up in s3 and starting to take up ~7TB or 12% of all storage...
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and …
=> Allow canary to delete objects from the results s3 bucket

README.md, cdk/lib/__snapshots__/commercial-canaries.test.ts.snap, cdk/lib/commercial-canaries.ts, cdk/package.json, cdk/yarn.lock, src/cmp_aus.js, src/cmp_ccpa.js, src/cmp_tcfv2.js
- Use latest puppeteer version
- Bumps Guardian CDK and AWS CDK dependencies
- Fix a few mistakes in the comments
=> Bump puppeteer to v3.9

src/cmp_aus.js, src/cmp_ccpa.js
In september a change was introduced by SP that required us to add a delay after interacting with the CMP to allow SP to persist the change. The delay was added here: https://github.com/guardian/commercial-canaries/pull/32
Since then the change seems to be 'saved' faster and such a long timeout should no longer be required.
=> Reduce the timeouts on action for CCPA

cdk/lib/__snapshots__/commercial-canaries.test.ts.snap, cdk/lib/commercial-canaries.ts, src/cmp_tcfv2.js
I'm making changes to both the CDK stack and the lambda in an attempt to force both to rebuild and redeploy.
The changes themselves are not significant but:
- The failure retention period is increased from 30 to 31 days
- The log message on clicking "Yes I'm Happy" changes from `Clicking on "Yes I'm Happy" on CMP` to `Clicking on "Yes I'm Happy"`
=> Insignificant changes to force redeploy

README.md, cdk/lib/__snapshots__/commercial-canaries.test.ts.snap, cdk/lib/commercial-canaries.ts
- Update synthetics version to 4.0.
- Remove Node 14 advice from README.
Log in the the AWS console and check that the canaries are still working.
=> Bump synthetics version

README.md
- Update README to remove step to ask comdev for access to release diagram
There is no need for this deck to be locked down to comdev. We have updated the permissions to give everyone in the Guardian access
=> Remove step to ask comdev for access to release diagram

src/cmp_aus.js
We're investigating whether or not there is a delay in persisting the user's consent choice in SourcePoint in Australia. This time delay was originally added to prevent canary failures, due to the delay in the consent choice being persisted.
We believe the issue with the consent choice being delayed should be fixed, so we'd like to verify this by removing the waitForTimeout in the interactWithCMP function in Australia. At the moment, T&C's monitoring is out of action, so it makes sense for us to test this here.
If the canary begins to fail, then we'll know that this delay still exists. If the canary still passes, then we'll know that the consent choice delay issue has been resolved.
=> Remove waitForTimeout in Aus interactWithCMP

src/cmp_ccpa.js
Waits for the page to reload after clicking "Do not sell my personal information" before trying to inspect the DOM. We currently have a timeout after clicking this, which I believe is why the canary is still managing to pass sometimes as there can be just enough time for the page to reload before checking that the CMP isn't visible. This change handles that wait explicitly.
I've tested this on CODE and it looks pretty stable:
=> Handle page reload after consent change for CCPA canary

cdk/package.json, cdk/yarn.lock
This PR forces dependency to resolve to a new `ws` version to resolve dependency high vulnerability.
=> Upgrade ws to 7.5.10

cdk/package.json, cdk/yarn.lock
This PR forces dependency to resolve to a new `node-fetch` version to resolve dependency high vulnerability.
=> Upgrade node-fetch to 2.6.7

src/cmp_aus.js, src/cmp_ccpa.js, src/cmp_tcfv2.js
Add prebid checks from our E2E tests to our Canaries.
We have added more checks to test the needs from the E2E tests:
- check if prebid.js is loaded
- check if PBJS is loaded in the window
-  check fr bid response
- Updated for all regions UK, US, AU
- takes into account CA and not testing prebid
Testing can be done by deploying to CODE and checking in AWS Synthetics:
https://github.com/guardian/commercial-canaries?tab=readme-ov-file#development
That all checks pass and successful logging for accurate debugging.
co-authored: @cemms1
=> adds canaries checks for new prebid tests

src/cmp_tcfv2.js
This checks for the currentLocation, before the check for the prebid bundle. This is a slight retrospective fix to the related PR [here](https://github.com/guardian/commercial-canaries/pull/68).
Deploy manually to AWS synthetics CODE in canada region `ca-cenral-1`.
=> move canada location check before prebid bundle test

cdk/lib/__snapshots__/commercial-canaries.test.ts.snap, cdk/lib/commercial-canaries.ts, cdk/package.json
This PR fixes the email subscription alert that wasn't working when CloudWatch is in the `ALARM` state for `us-west-1`, `ca-central-1` and `ep-southeast-2`. It was only working for `eu-west-1`. 
The solution is still a mystery which is adding an alias to the Subscription email endpoint for each region.
If you check the AWS Topic in commercial-canaries CODE for each region you will find the subscription associated with it has a _Status_ `confirmed`. There is no way to test it in PROD until we merge this PR and we should receive new Subscription confirmation emails for each region. For testing our changes in PROD we can trigger the `ALARM` state in any of the previously non working regions to make sure it works!
We get notified through email alerts for any of the specified regions whenever …
=> Fix email alert for UK, EU, US regions 
